#pragma once

#define WIRELESS_BAUDRATE 38400

// TEST LED
#define TEST_LED_ON HAL_GPIO_WritePin(TEST_LED_GPIO_Port, TEST_LED_Pin, GPIO_PIN_RESET)
#define TEST_LED_OFF HAL_GPIO_WritePin(TEST_LED_GPIO_Port, TEST_LED_Pin, GPIO_PIN_SET)

// BUTTON
#define BUTTON_DEBOUNCE_TIME 20
#define BUTTON_WAIT_FOR_HOLD_TIME 1000
#define BUTTON_REPEAT_INTERVAL 100

#define MAX_ON_HOLD_FUNCTIONS 5

#define SERVO_TEST_HOLD_TIME 4000
#define MOTOR_TEST_HOLD_TIME 6000

// SERWO
#define SERVO_DATA_MAX_DELAY 200
#define SERVO_MIN_POSITION 950
#define SERVO_ZERO_POSITION 1500
#define SERVO_MAX_POSITION 2050

// MOTOR
#define MOTOR_DATA_MAX_DELAY 200

// ADC Parameters
#define ADC_CONVERSION_COUNT 2
#define MAX_ADC_RAW_VALUE 4096

#define MICROCONTROLLER_VOLTAGE 3.3f

#define R1_MAIN_SUPPLY 10000.0f
#define R2_MAIN_SUPPLY 1000.0f
#define R1_DC_MOTOR 4700.0f
#define R2_DC_MOTOR 1000.0f
